# Generated by Django 5.1.6 on 2025-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='assigned_students', through='base.project_studnet', to='base.student'),
        ),
    ]
