# Generated by Django 5.1.6 on 2025-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student_created_at_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=255),
        ),
    ]
