# Generated by Django 5.1.6 on 2025-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
