# Generated by Django 5.1.6 on 2025-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_dataset_description_alter_dataset_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('important', 'Important'), ('general', 'General')], max_length=20, null=True),
        ),
    ]
