# Generated by Django 5.1.6 on 2025-06-18 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='students-cv'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student-profile'),
        ),
    ]
