from django.urls import path,include
from . import views
urlpatterns = [
    path('dashboard/',views.dashboard, name="home"),
    path('datasets/',views.dataset, name="dataset"),
    path('create-dataset/',views.create_dataset, name="create_dataset"),
    path('',views.landing_page, name="landing_page"),
    path('explore/',views.explore, name="explore"),
    path('create-project/', views.create_project, name="create_project"),
    path('details-project/<int:pk>', views.project_detail, name="project_detail"),
    path('update-project/<int:pk>', views.update_project, name='update_project'),
    path('student-profile/<int:pk>', views.view_student_profile, name='view_profile'),
    path('teacher-profile/<int:pk>', views.teacher, name='teacher_profile'),
    path('register/', views.student_register, name='student_register'),
    path('login/', views.student_login, name='student_login'),
    path('teacher-login/', views.teacher_login, name='teacher_login'),
    path('logout/', views.student_logout, name='student_logout'),
    path('approvals/', views.pending_approvals, name='pending_approvals'),
    path('approve/<int:student_id>/', views.approve_student, name='approve_student'),
    path('profile-update/', views.update_student_profile, name='update_student_profile'),
    path('team/', views.team, name='team'),
    path('team-member-details/<int:id>', views.team_member_details, name='team_member_details'),
    path('all-member/', views.all_member, name='all_member'),
    path('download-dataset/<int:dataset_id>/', views.download_dataset, name='download_dataset'),
    path('dataset-details/<int:dataset_id>/', views.dataset_download_history, name='dataset_download_history'),
    path('latest-news/', views.latest_news, name='latest_news'),
    path('create-news/', views.create_news, name='create_news'),
    path('teacher-register/', views.teacher_register, name='teacher_register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]
